### PR TITLE
Invoke delegate the stream(_ stream: NetStream, didOutput video: CMSa…

### PR DESCRIPTION
**Pull request by shogo4405**
…mpleBuffer) method.

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by zaliva08** [comment]
After the changes you made, for me still do not work out the delegate and does not come CMSampleBuffer.
    override func viewDidLoad() {
        super.viewDidLoad()
        rtmpConnection.delegate = self
        rtmpStream.delegate = self
    }
extension MAnchorVC: NetStreamDelegate {
    func stream(_ stream: HaishinKit.NetStream, didOutput video: CMSampleBuffer) {
        guard !self.isStopped else { return }
        XMagicManager.share().processData(withCpuFuc: video)
    }
    
    How else can I get CMSampleBuffer ?

**Comment by zaliva08** [comment]
Add please delegate?.mixer(self, didOutput: sampleBuffer)
  You should do this in func useSampleBuffer
    
    func useSampleBuffer(sampleBuffer: CMSampleBuffer, mediaType: AVMediaType) -> Bool {
        switch mediaSync {
        case .video:
            if mediaType == .audio {
                return !videoTimeStamp.seconds.isZero && videoTimeStamp.seconds <= sampleBuffer.presentationTimeStamp.seconds
            }
            if videoTimeStamp == CMTime.zero {
                videoTimeStamp = sampleBuffer.presentationTimeStamp
            }
            delegate?.mixer(self, didOutput: sampleBuffer)
            return true
        default:
            return true
        }
    }

**Comment by shogo4405** [comment]
This feature is primarily designed for the behavior during playback and becomes part of the specification.

**Comment by zaliva08** [comment]
I had to implement a library of effects. I needed SampleBuffer for this from rtmpStream. By adding this delegate in library I was able to get the result I need. 

But I added the library HashimKit as static because of this. It would be nice if you would correct yourself then I will go back to use Cartfile

**Pull request merged**
