### PR TITLE
Improve audio channel mapping

### PR DESCRIPTION
**Pull request by leo150**
## Description & motivation

* Fix audio channel mapping. My previous implementation was creating a channel map of size n, where n is number of input channels. It should use number of output output channels instead.
* Expose channel map for external use
* Add channel map unit tests

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by leo150** [comment]
I added unit tests. `makeChannelMap` falls back to default value if the provided one is incorrect.

**Comment by shogo4405** [comment]
I just noticed after the merge that the tests are failing. Is the expected outcome correct?
スクリーンショット 2023-09-02 15 55 58

**Comment by leo150** [comment]
Hey, thank you for noticing this. The test is incorrect, it should expect [0, -1]. I checked again, it's the only test that is failing. Thanks.

**Comment by shogo4405** [comment]
Okay, I've fixed the tests. [2e1cb55](https://github.com/shogo4405/HaishinKit.swift/commit/2e1cb551795d3441ba842ca6223693dbe7ea5864)

**Pull request merged**
