### PR TITLE
Start recording when needed

### PR DESCRIPTION
**Pull request by pvinis**
i want to be able to start streaming first, and start recording later.

### CODE REVIEW

**Comment by shogo4405** [comment]
Wowza(FMS) can server side recording. publish("foo", "record" | "append" | "appendWithGap")

You can start recording.
publish("foo") then publish("foo", .localRecord)

I do not want to increase methods.

**Comment by pvinis** [comment]
I know wowza can do stuff. this is for local recording. I didn't know I can publish twice. then I will try it. but it's it going to be slower/harder on the phone? will the frame processing happen twice with two publish?

**Comment by shogo4405** [comment]
I designed...
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPStream.swift#L422-L432

> but it's it going to be slower/harder on the phone
It is a bug. I will try fix.

**Comment by pvinis** [comment]
ok thanks for the answer. I will try it and then maybe I give a PR with some refactoring so you check it too. I want to help you make this lib better :)

**Comment by purvangi-dev** [comment]
Is recording in between live streaming working? Can you share working samples please?

**Pull request closed without merging**
