### PR TITLE
Add the movieFragmentInterval value to the recording feature.

### PR DESCRIPTION
**Pull request by shogo4405**
## Description & motivation
- It possible to specify the movieFragmentInterval to recover from crashes or unintended task termination.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by mkrn** [comment]
Thank you for adding this! 
I'm looking at the documentation 
https://developer.apple.com/documentation/avfoundation/avcapturemoviefileoutput/1387146-moviefragmentinterval
and it looks like it is 10s by default.. but the files are still sometimes unusable with crash.. was this feature disabled before?

**Comment by shogo4405** [comment]
I have never implemented this before, so it will be a new implementation.

There are APIs using iOS that include [AVAssetWriter](https://developer.apple.com/documentation/avfoundation/avassetwriter) and [AVCaptureMovieFileOutput](https://developer.apple.com/documentation/avfoundation/avcapturemoviefileoutput). HaishinKit uses [AVAssetWriter](https://developer.apple.com/documentation/avfoundation/avassetwriter). 

In the case of AVAssetWriter, the default value for this is set to invalid.
https://developer.apple.com/documentation/avfoundation/avassetwriter/1387469-moviefragmentinterval

**Comment by shogo4405** [comment]
I see, so it's unstable when it crashes. I was testing with Task Kill.
It seems like further research is needed, but for now, I believe this is the right specification and it will improve from here. I'll merge it for the time being.

**Comment by mkrn** [comment]
Thank you this worked! It could be even 10.0s by default 
Thank you for pointing out that it was invalid in AVAssetWriter.

**Pull request merged**
