### PR TITLE
Add did publish sufficient BW

### PR DESCRIPTION
**Pull request by dawidvdh**
Busy working on a adaptive bitrates, `RTMPStreamDelegate` provides a way to lower the bitrate however I need a way to up the bitrate and I think this solution might work.

Usage:

```swift
let minBitrate: UInt32 = 300 * 1024
let maxBitrate: UInt32 = 2500 * 1024
let incrementBitrate: UInt32 = 512 * 1024

class MyRTMPStreamDelagate: RTMPStreamDelegate {
	@objc var onBWStatusChange: RCTDirectEventBlock?
	
	func didPublishInsufficientBW(_ stream: RTMPStream, withConnection: RTMPConnection) {
		guard var videoBitrate = stream.videoSettings["bitrate"] as? UInt32 else { return }
		print("didPublishInsufficientBW \(videoBitrate)")
		
		videoBitrate = UInt32(videoBitrate / 2)
		if videoBitrate < minBitrate {
			videoBitrate = minBitrate
		}
		stream.videoSettings["bitrate"] = videoBitrate
	}
	
	func didPublishSufficientBW(_ stream: RTMPStream, withConnection: RTMPConnection) {
		guard var videoBitrate = stream.videoSettings["bitrate"] as? UInt32 else { return }
		print("didPublishSufficientBW \(videoBitrate)")
		
		videoBitrate = videoBitrate + incrementBitrate
		if videoBitrate > maxBitrate {
			videoBitrate = maxBitrate
		}
		stream.videoSettings["bitrate"] = videoBitrate
	}
	
	func clear() {
	}
}
```

### CODE REVIEW

**Comment by dawidvdh** [comment]
Just noticed that it eats the CPU, gonna try attempt to find an alternative way

**Comment by mkrn** [comment]
Hi Dawid, 
Here's how we've ended up doing it: 
Every second we raise bitrate by 64kbps if it's under default. And once insufficientBW triggered we divide it in 2 like in examples:

```

timer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: #selector(periodicalTasksLaunch), userInfo: nil, repeats: true)

@objc func periodicalTasksLaunch() {
  if let curBitrate = rtmpStream.videoSettings["bitrate"] as? Int {
      bitrate = min(curBitrate + 64 * 1_024, Constants.streamVideoBitrate)
      rtmpStream.videoSettings["bitrate"] = bitrate
    }
}
```

**Comment by dawidvdh** [comment]
@mkrn but dont you feel like having it bundled with `RTMPStreamDelegate` and not having to implement a custom timer would be a better solution? Or am I doing something horribly wrong (learning swift as I go so this is very possible).

**Comment by shogo4405** [comment]
👍

**Pull request merged**
