### PR TITLE
Effects as array to execute them in known order

### PR DESCRIPTION
**Pull request by eerimoq**

### CODE REVIEW

**Comment by eerimoq** [comment]
Why no merge? Anything more I have to do? Thanks.

**Comment by shogo4405** [comment]
I couldn't evaluate the PR because it doesn't have any documentation content.

**Comment by eerimoq** [comment]
Ok, I'll try to explain.

Registered video effects are currently stored in a set. Iterating over a set yields items in an undefined order. This PR replaces the set with an array to guarantee that the effects are executed in the same order as registered by the user.

**Comment by eerimoq** [comment]
@shogo4405 Feel free to review again. Thanks!

**Comment by eerimoq** [comment]
@shogo4405 Sorry for spam. I added documentation in the first PR comment. Would be happy if you can review again. Thanks.

**Comment by levs42** [comment]
@shogo4405 could you please take a look at this PR? It's useful when the effects should be executed in a specific order. If Array isn't a good option, I can add [OrderedSet](https://github.com/apple/swift-collections/blob/main/Sources/OrderedCollections/OrderedSet/OrderedSet.swift) from Apple's collection. Thanks.

**Comment by levs42** [comment]
@eerimoq could you please submit a new PR?

**Pull request closed without merging**
